### ISSUE TITLE
block time not stable

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/linea-besu#35]
Besu is configured with a block time of 4s, but more than 4s ellapse between two blocks. It seems that the timer for block creation does not start right after the previous block was produced as shown in these logs:

![image](https://github.com/Consensys/linea-besu/assets/3274281/90fa2097-1cb4-416c-bef1-7d7c3aa3b510)

**Comment by fab-10** [comment]
Which is the value of `poa-block-txs-selection-max-time'?

**Comment by fab-10** [comment]
Evaluate the correlation between the increase of `tx-pool-max-prioritized` to 32000 and this.

Green is 16k, blue is 24k, yellow is 32k
![image](https://github.com/Consensys/linea-besu/assets/91944855/80152476-36dd-4f7f-af17-dc97e6fdbd06)
