### ISSUE TITLE
besu node rpc returns data exception

### ISSUE THREAD

**Issue by rayn316** [Consensys/linea-besu#39]
os: ubuntu 22.04
network: mainnet
bin: `./besu-24.3.0/bin/besu --config-file=/node/full/linea/bin/config-mainnet.toml`

There is a problem with besu software debug_traceBlockByHash  debug_traceBlockByNumber. Compared with geth, the data returned is abnormally large at certain times.
besu returns 200MB+ data (Some blocks are even larger)
geth returns 92KB data
```
curl --location --request POST '127.0.0.1:8545' \
--header 'Content-Type: application/json' \
--data-raw '{"method":"debug_traceBlockByHash","params":["0x908dc81be1f01948e7c002407e36c8401bf301d48e979e04a512e7513af79d13", {"tracer": "callTracer"}],"id":1,"jsonrpc":"2.0"}'
```

![image](https://github.com/Consensys/linea-besu/assets/24621599/1d82c769-d23e-43bd-b75c-15b0b5d253d4)

**Comment by Gabriel-Trintinalia** [comment]
Maybe `disableMemory` could help?

**Comment by rayn316** [comment]
How to disable Memory
I don’t see it in the command help, what should I do?

**Comment by rayn316** [comment]
There is still a problem in the return. After turning on disableMemory, it is still very large. After turning off all three projects, the data is all meaningless.

```
curl -Ls -X POST -H 'Content-Type: application/json' -d '{
   "jsonrpc":"2.0",
   "method":"debug_traceBlockByHash",
   "params":[
      "0x0db7b4ae8fe16ddbeb676e0cfdcb2728f0eac64d25905e0887b178edf619fae4",
      {
         "disableMemory":true,
         "disableStorage":true,
         "disableStack":true
      }
   ],
   "id":1
}' 'http://127.0.0.1:8545'
```

![image](https://github.com/Consensys/linea-besu/assets/24621599/42488257-71c7-4058-9ed6-565c11acb780)
![image](https://github.com/Consensys/linea-besu/assets/24621599/1d6fb343-8c58-47b6-8e96-4aeeb3228391)
![image](https://github.com/Consensys/linea-besu/assets/24621599/ea442e0d-c196-4241-b67f-0fcc27cfcefd)

**Comment by Gabriel-Trintinalia** [comment]
Could you please post what you are seeing with Geth

**Comment by rayn316** [comment]
![image](https://github.com/Consensys/linea-besu/assets/24621599/5645c828-78db-4d33-a58b-0ea5cd411892)
[info.txt](https://github.com/Consensys/linea-besu/files/14831034/info.txt)

**Comment by manofthemooon** [comment]
Issue with the size of the data returned by the debug_traceBlockByHash and debug_traceBlockByNumber methods in Besu compared to Geth, particularly when dealing with certain blocks. While Geth returns data in the range of kilobytes, Besu returns significantly larger data, sometimes exceeding 200MB.
